#!/bin/sh
#

load_drivers()
{
	while IFS= read -r line; do
		modprobe $line
	done < "/etc/modules.autoload"
}

case "$1" in
	start)
		printf "Loading kernel modules:"
		load_drivers
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
